# Generated by Django 5.0.6 on 2024-07-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.DecimalField(decimal_places=0, max_digits=2)),
                ('specialization', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=0, max_digits=5)),
                ('timings', models.CharField(max_length=20)),
                ('charge', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
