# Generated by Django 5.0.6 on 2024-07-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('medical_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hospital_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discharge_date', models.DateField()),
            ],
        ),
    ]
